
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("*   *   *   *   *   *   *   ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("*   *   *   *   *   *   *   ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("  *   *   *   *   *   *   * ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("  *   *   *   *   *   *   * ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("*   *   *   *   *   *   *   ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("*   *   *   *   *   *   *   ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("  *   *   *   *   *   *   * ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("  *   *   *   *   *   *   * ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("*   *   *   *   *   *   *   ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("*   *   *   *   *   *   *   ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("  *   *   *   *   *   *   * ");
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Write("  *   *   *   *   *   *   * ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.White;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Write("                            ");
    Console.BackgroundColor = ConsoleColor.Red;
    Console.WriteLine("                                       ");
    Console.BackgroundColor = ConsoleColor.Black;
    Console.Write("                            ");